### ISSUE TITLE
Advancement spam in disabled world, possible datapack cause

### ISSUE THREAD

**Issue by LadyHaley** [jairusudanieru/AdvancementBlocker#1]
I dont know if its because im using a datapack or not but this seems like a bug
There is no console errors and it occurs in a world with advancements disabled
It will span this for as long as I am standing on a pressure plate
[This is the datapack im using](https://www.planetminecraft.com/data-pack/blazeandcave-s-advancements-pack-1-12/)
![2023-09-26-18-55-14](https://github.com/jairusudanieru/AdvancementBlocker/assets/3754909/92b4ca5b-fe0f-4868-9943-d9c751635352)

**Comment by jairusudanieru** [comment]
I tried to recreate the issue and found out it's actually the plugin's fault. I tried to [fix it](https://github.com/jairusudanieru/AdvancementBlocker/releases/tag/v1.0.1) by only blocking (revoking after you get it) vanilla advancements, but it seems the datapack you're using also uses a vanilla advancement that might spam you when you get one. So I can tell that the datapack is not fully compatible with this plugin. [check this video](https://imgur.com/6DPpf4R)

**Comment by LadyHaley** [comment]
Ah yeah, I think datapacks that add items as rewards for advancements use some sort of regular interval checking for some of the advancements with the rewards that I suspect would cause that issue. I tried finding a datapack blocker similar to this plugin but couldnt find one.  Ill have to look more into blocking the datapack for a certain world in paper when i have more time, hopefully its an easy fix lol
